In [69]:
#numpy is used to creat array and do mathmatical calculation
#https://numpy.org/devdocs/user/
 
!pip install numpy



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
L=[1,1.2,'amit']
L


[1, 1.2, 'amit']

In [67]:
type(L)

list

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr[0]

1

In [8]:
arr[2]

3

In [11]:
arr[0],arr[1],arr[2]

(1, 2, 3)

In [ ]:
arr[0] #element present at index 0 
 #element present at index 1
#element present at index 2

In [12]:
arr[0]-arr[1]

-1

In [13]:
arr[1]-arr[0]

1

In [14]:
arr[1]*arr[0]

2

In [16]:
import numpy as np 
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
import numpy as np 
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
#it is telling you number of rows and column (Row,Column)
array2.shape

(3, 4)

In [34]:
import numpy as np 
array3=np.array([[1,2,3,8],[5,6,7,8],[9,10,11,5]])
array3

array([[ 1,  2,  3,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  5]])

In [28]:
#for loop
import numpy as np 
array3=np.array([[1,2,3,8],[5,6,7,8],[9,10,11,78]])
array3


array([[ 1,  2,  3,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 78]])

In [29]:

#loop
for i in array3:
    print(i)

[1 2 3 8]
[5 6 7 8]
[ 9 10 11 78]


In [40]:
import numpy as np

array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11,12]])


for i in array3:
    for j in array3:
        print(i,j)

[1 2 3 4] [1 2 3 4]
[1 2 3 4] [5 6 7 8]
[1 2 3 4] [ 9 10 11 12]
[5 6 7 8] [1 2 3 4]
[5 6 7 8] [5 6 7 8]
[5 6 7 8] [ 9 10 11 12]
[ 9 10 11 12] [1 2 3 4]
[ 9 10 11 12] [5 6 7 8]
[ 9 10 11 12] [ 9 10 11 12]


In [44]:
for i in array3:#i will be assigned with 3 #first for loop for reading every row of an array 
    for j in i: #j will run 3 times #second for loop for reading every value of that particular row
        print(j , end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [46]:
for i in np.nditer(array3): #nditer here nd means n dimentions, numpy function which iterate value un n-dimension  
    print(i , end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [49]:
#where function is used to search element here we are searching element 4 
array4 = np.array([1,2,3,4,5,4,4])
x=np.where(array4==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [50]:
array5=np.array([11,2,13,4,5,44,94])
print(np.sort(array4))

[1 2 3 4 4 4 5]


In [55]:
array5=np.array([11,2,13,4,5,44,94])
print(np.sort(array4))

[1 2 3 4 4 4 5]


In [57]:
x=np.sort(array5)
x[: : -1] #print in descending order

array([94, 44, 13, 11,  5,  4,  2])

In [59]:
x[-1 :]

array([94])

In [61]:
#print random number
from numpy import random
a=random.randint(100)#0 to 100
a

18

In [66]:
from numpy import random

for i in range(1,20):
    a=random.randint(100)#0 to 100
    print(a, end=" ")

66 48 77 5 17 59 6 26 40 4 55 87 23 99 82 11 42 43 94 